---
- name: Check IP connectivity
  hosts: localhost
  gather_facts: yes
  vars:
    input_file: "{{ input_file | default('hosts.txt') }}"
    output_file: output.txt
  tasks:
    - name: Install nc (netcat)
      package:
        name: "{{ 'nc' if ansible_os_family == 'Debian' else 'nmap-ncat' }}"
        state: present
      become: yes
      become_method: sodo  # Use 'su' instead of 'sudo'

    - name: Validate input_file variable
      assert:
        that:
          - input_file is defined
          - input_file | length > 0
        msg: "The input_file variable is not defined or empty."

    - name: Debug input_file value
      debug:
        msg: "input_file: {{ input_file }}"

    - name: Read IPs from file
      command: cat {{ input_file }}
      register: ip_list

    - name: Check IP connectivity
      shell: nc -vz {{ item }} 22 2>&1
      register: result
      with_items: "{{ ip_list.stdout_lines }}"
      ignore_errors: yes

    - name: Write results to output file
      copy:
        content: |
          {% for item in result.results %}
          {{ item.item }}: {{ 'success' if item.stdout is defined and 'Connected' in item.stdout else 'failed' }}
          {% endfor %}
        dest: "{{ output_file }}"

    - name: Print results
      debug:
        msg: "Output file generated: {{ output_file }}"
