---
- name: Ping hosts from GitHub file
  hosts: localhost
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: 'https://github.com/bart-kus/AWX.git'
        dest: /tmp/bart-kus

    - name: Read IP addresses from file
      command: cat /tmp/bart-kus/AWX/hosts.txt
      register: ip_list

    - name: Ping each host
      ansible.builtin.ping:
      with_items: "{{ ip_list.stdout_lines }}"
      loop_control:
        loop_var: ip
